version: '3.7'

services:
  web:
    build:
      context: ./
    image: forddock:latest
    command: gunicorn --bind 0.0.0.0:5000 manage:flask_app
    ports:
      - 8000:5000
    env_file:
      - ./.env
    environment:
      ENVIRONMENT: "${ENVIRONMENT}"
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    expose:
      - 5432
volumes:
  postgres_data:
